name: Deploy Portfolio
on:
  push:
    branches: [master] # 確認是 master 分支
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SASS
        run: sudo apt-get install -y sass
      - name: Compile SCSS
        run: sass src/style.scss src/style.css
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "src" # 因為你的檔案在 src 裡
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
